on: [push]

jobs:
    view:
        runs-on: ubuntu-22.04
        steps:
        - run: echo "Hello, World!"
        - run: ls
    show:
        runs-on: ubuntu-22.04
        steps:
        - run: echo "Hello, World!"
        - run: ls -a
        - run: pwd
